package com.aaatech.iap.enums;

public enum Response {
	// success
	SUCCESSFUL, ALREADY_PURCHASED, 
	INVALID_SKU, NULL_OR_EMPTY_INPUT, SUCCESSFUL_WITH_UNAVAILABLE_SKUS,
	PURCHASE_VIRIFICATION_FAILED,
	// samsung
	APP_NOT_FOUND, BINDING_ERROR, AUTH_CANCELLED,
	//bb
	BILLING_NOT_SUPPORTED,
	FAILED;
	
}